### PR TITLE
modified makefile to make Entitlements works

### PR DESCRIPTION
**Pull request by iMokhles**

### CODE REVIEW

**Comment by coolstar** [comment]
did you even try the app to see if it works? the entitlements are applied by ldid but the app crashes on launch if entitlements are in place

**Comment by iMokhles** [comment]
i didn't even update my device till now ( but if the issue from the Entitlements file it self, so there are redefinition entitlement are applied )

**Comment by coolstar** [comment]
OpenSettings works on iOS 8.1.x as well, no need to update the device to test.

**Comment by iMokhles** [comment]
great i will test it now ;)

**Pull request closed without merging**
